import React from 'react';

interface Props {
  activeItem: string;
}

export const Content: React.FC<Props> = ({ activeItem }) =>
  <>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida est elementum, viverra velit sed, posuere erat. Etiam molestie pretium justo. Duis euismod, dolor at bibendum pretium, velit urna elementum enim, in placerat quam ante sed ante. Mauris nec purus nec augue semper ornare vitae a sapien. Maecenas ut commodo diam, id finibus neque. Integer aliquet lorem eget eros interdum tincidunt. In vel tortor ut lacus commodo tincidunt.

Morbi cursus ultricies est ac sagittis. Integer fermentum hendrerit orci quis accumsan. Praesent id gravida ligula, ac accumsan erat. Ut at dolor vel nisl porttitor dapibus. Nullam scelerisque dictum sem, eget placerat libero faucibus sed. Vestibulum tristique posuere nibh, ac euismod nibh faucibus eget. In posuere nibh iaculis diam vulputate, quis dictum metus luctus. Cras libero nibh, placerat eu risus ac, fringilla mollis leo.

Pellentesque iaculis tortor at varius pharetra. Integer in nunc rutrum, auctor libero at, semper lacus. Integer nec augue a risus ultrices faucibus vel a ante. Donec faucibus nulla quis venenatis posuere. Ut iaculis, tellus id molestie pharetra, magna leo elementum enim, et commodo lorem lorem at lectus. In pellentesque magna eu nunc rhoncus, quis euismod tortor porttitor. Nulla fermentum nibh id odio iaculis, quis tempus ipsum commodo. Nam a bibendum leo. Vestibulum efficitur, est pharetra imperdiet ultricies, tortor augue mattis nisi, in faucibus justo risus vestibulum libero. Donec est eros, convallis eu sapien eget, gravida tincidunt libero. Donec nec magna mauris. Suspendisse potenti. Nullam lobortis congue ligula, aliquet cursus orci consectetur quis. Etiam ullamcorper, est sed pellentesque consectetur, nibh lorem iaculis velit, a tempus tellus lorem ac sem. Nullam convallis, ex sit amet ornare tincidunt, nunc turpis tempus elit, a egestas nunc tellus at nulla.

Nulla facilisi. Nullam ac rutrum erat. Maecenas a mauris non mi ultrices tempor sed a tortor. Nunc facilisis pharetra ultricies. Ut scelerisque nibh ullamcorper, dictum ex efficitur, molestie sem. Integer non lacus et dolor feugiat varius at ut magna. Phasellus suscipit congue nisl, vel placerat nunc accumsan at. Vivamus sed tincidunt justo. Maecenas commodo erat turpis, at convallis eros imperdiet in. Nullam dictum iaculis leo, nec fringilla lacus pretium egestas. Integer urna sapien, placerat at libero ut, pharetra eleifend elit. Phasellus massa sem, dictum a est a, pellentesque gravida libero.

Sed elementum ligula id dui tempor pellentesque. Donec maximus neque ut faucibus venenatis. In sodales a dolor at convallis. Vivamus risus risus, euismod non convallis eget, placerat ut nibh. Duis eget volutpat sem. Ut vestibulum nec metus eu dignissim. Vestibulum vel nibh maximus, dignissim erat interdum, bibendum urna. Praesent vel purus non felis facilisis pretium. Nunc auctor tristique tortor, a dapibus arcu. Nam aliquet sem sed nulla ornare placerat. Phasellus vitae imperdiet ipsum. Suspendisse laoreet elit sit amet arcu faucibus rutrum.

Duis eu quam vitae magna semper blandit sed sed turpis. Praesent vehicula, neque non fringilla pretium, diam arcu consequat libero, at pretium elit ex nec ligula. Duis non elit tincidunt, tempus felis a, condimentum massa. Morbi accumsan, arcu a aliquam faucibus, leo neque faucibus orci, nec rhoncus urna metus eu ligula. Duis et interdum lacus. Ut a aliquet neque, eget rutrum nisl. Curabitur neque augue, porttitor eget interdum quis, auctor eget purus. Nam placerat elementum sem luctus maximus. Phasellus tincidunt justo sit amet tellus auctor pretium. Nam ac ultricies enim. Etiam dictum velit commodo neque placerat, non sagittis ante laoreet. Integer id viverra dui, vitae tincidunt lorem.

Aliquam erat volutpat. Sed eget imperdiet nulla. Phasellus vestibulum ultrices aliquam. In tempus lacinia felis quis consequat. Nunc quis viverra sapien, a aliquam metus. Maecenas in mattis eros. Nunc leo sem, fermentum vitae rhoncus mattis, lobortis in lacus. Sed ultricies cursus enim, ac maximus lacus dictum sed. Praesent mattis tortor eget purus pellentesque finibus. Maecenas interdum sapien lacus, nec gravida nisi lacinia id. Nullam ac vestibulum lacus. Quisque lorem ipsum, facilisis id odio et, facilisis interdum augue.

Etiam ac efficitur nibh, eget tincidunt eros. Nam tincidunt turpis at orci ullamcorper lacinia. Sed consequat dictum ligula suscipit rhoncus. Proin luctus turpis non neque elementum, in efficitur massa imperdiet. Mauris tempus volutpat enim, non ultrices nisl cursus non. Integer nisl nibh, laoreet placerat bibendum at, semper id sem. Praesent id justo massa. Nunc neque neque, convallis sit amet placerat et, mollis vitae dolor. Pellentesque volutpat et lacus et rhoncus. Vivamus maximus ipsum sit amet felis semper, ut sodales nulla feugiat. Curabitur felis arcu, blandit quis mi in, lacinia iaculis odio.

Phasellus eu purus ac quam vehicula facilisis non in risus. Fusce iaculis odio ac augue placerat dignissim. Suspendisse placerat arcu tempor arcu scelerisque tristique. Sed in eros velit. Nunc tristique hendrerit condimentum. Quisque interdum pellentesque arcu, a fringilla odio. Maecenas finibus aliquam quam sit amet interdum. Integer imperdiet eros ante. Pellentesque fringilla, nunc sit amet aliquet commodo, leo arcu fermentum ex, condimentum molestie turpis sapien quis lacus. Fusce placerat massa id orci sollicitudin gravida. Etiam non nulla enim. Ut venenatis dignissim tellus at sollicitudin. Pellentesque sodales auctor pulvinar. Fusce fermentum dictum ante, eu venenatis metus vulputate hendrerit. Fusce nec diam sed ligula commodo rhoncus ut feugiat ligula.

Donec consequat consequat vehicula. Pellentesque consectetur luctus ipsum vitae vulputate. Aenean velit lorem, efficitur eget sodales nec, iaculis et tortor. Vestibulum feugiat velit sem, eu consequat purus mattis nec. Praesent massa leo, pretium vel ullamcorper sit amet, pharetra nec sem. Fusce ultricies nisi ut lorem suscipit blandit vitae eget ante. Maecenas tincidunt pellentesque nunc, id placerat erat finibus at.

Mauris nec feugiat tellus. Donec at feugiat urna. Donec rutrum, nisi nec volutpat placerat, felis leo tristique dolor, a molestie mi libero fermentum augue. Nam sit amet lobortis massa. Cras quam odio, elementum eget lacus in, facilisis ullamcorper leo. Donec aliquet volutpat posuere. Aenean at bibendum metus, quis maximus arcu. Curabitur mi turpis, lobortis sed pharetra ut, auctor in magna. Praesent nec dictum ipsum. Nunc sed velit sem. Integer eget lectus id eros vehicula sagittis et quis felis.

Sed tempus id ligula vitae consectetur. In finibus feugiat quam eu rhoncus. Curabitur vitae odio blandit, bibendum lacus in, pharetra risus. Duis viverra placerat diam, in feugiat quam fringilla nec. In ac ultricies turpis. Phasellus blandit consectetur faucibus. Proin vitae ultricies massa. Etiam in euismod libero, elementum fermentum justo. Pellentesque hendrerit id felis ac volutpat. Nunc augue orci, finibus ultricies tincidunt et, posuere at lorem. Sed felis magna, laoreet in lorem at, scelerisque varius quam. Curabitur ullamcorper eros lectus. Mauris sodales sapien diam, ultrices molestie nulla fringilla nec. Aliquam at laoreet dui. Mauris eu felis a velit blandit maximus a non dolor. Proin augue augue, porttitor eget scelerisque eget, lacinia et turpis.

Praesent sagittis, urna non tristique facilisis, dolor ligula vestibulum eros, sit amet cursus orci ante sed nibh. Etiam a orci est. Nunc a cursus lectus. In convallis dolor vitae erat cursus elementum. Donec mattis fermentum magna non lacinia. Vestibulum pellentesque turpis orci, quis mattis neque suscipit in. Sed suscipit maximus sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ac lectus eleifend, dictum lacus sed, sodales nibh. Nulla neque felis, ultrices vel tortor a, viverra rutrum enim. Phasellus pulvinar ut diam vehicula tempus.

Sed at tincidunt lacus. Nulla semper eleifend erat, ut bibendum diam iaculis vitae. Pellentesque vitae condimentum urna. Nam fringilla magna purus, id vulputate velit facilisis eget. Quisque eu lectus a orci faucibus molestie et et turpis. Curabitur fringilla velit mollis ante hendrerit dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur quam est, viverra at metus eu, placerat luctus sem. Fusce pharetra nisi consectetur ex sodales, id dignissim orci sollicitudin. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean ac purus mollis odio lacinia euismod nec in urna. Nunc sit amet sem in nulla malesuada porttitor. Nullam suscipit eros interdum massa lobortis ullamcorper. Sed convallis pretium eleifend. Vestibulum mattis consectetur eros, ut venenatis sem ornare vel.

Maecenas a tempus ligula, in rutrum nisl. Proin ut odio urna. In aliquet, enim sed viverra consequat, velit mauris finibus purus, at volutpat ligula purus vel nisl. Suspendisse suscipit, enim id tempor tristique, diam lorem ullamcorper sem, eget posuere urna ligula ac purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras ornare nunc urna, eget consequat libero luctus a. Pellentesque eleifend lacinia congue. Etiam vitae urna molestie, volutpat tortor in, rutrum nulla. Sed eu enim imperdiet, aliquam ante vel, volutpat elit. Aenean fringilla consectetur nunc, at aliquam orci. Sed nec rhoncus sem. Pellentesque vulputate eros sit amet ligula aliquet, quis gravida ipsum blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus.
  </>
